unbind r
bind R source-file ~/.config/tmux/tmux.conf

set -g prefix C-Space

set -g mouse on

bind-key r command-prompt -I "#S" "rename-session '%%'"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top

set -g base-index 1
setw -g pane-base-index 1

# Fix nvim colors
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

# Status bar
set -g @plugin 'vaaleyard/tmux-dotbar'

# Use terminal colors
set -g @tmux-dotbar-bg "default"
set -g @tmux-dotbar-fg "colour7"
set -g @tmux-dotbar-fg-current "colour6"
set -g @tmux-dotbar-fg-session "colour7"
set -g @tmux-dotbar-fg-prefix "colour6"
set -g @tmux-dotbar-position top

# Pane borders using terminal colors
set -g pane-border-style "fg=colour8"
set -g pane-active-border-style "fg=colour6"

set-option -g default-shell /usr/bin/zsh

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
