### Setups
# starship
eval "$(starship init zsh)"
# zsh-autosuggestions
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
# case-insensitive + substring matching
autoload -Uz compinit
compinit
zstyle ':completion:*' matcher-list \
  '' \
  'm:{a-zA-Z}={A-Za-z}' \
  'r:|[._-]=* r:|=*' \
  'l:|=* r:|=*'

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

### ALIASES
alias vim="nvim"
alias lg='lazygit'
alias via='DISABLE_SUDO_PROMPT=1 via'
alias fetch='fastfetch'
alias zshconfig="nvim ~/.zshrc"
alias ls="eza"
alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
alias sv="source .venv/bin/activate"
alias zathura="zathura 2>/dev/null --fork"

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

### PATH
export MANPAGER='nvim +Man!'
export PATH=$HOME/.config/rofi/scripts:$PATH # rofi menus
export PATH="$HOME/.local/bin:$PATH"

### CONFIGURATIONS
# zsh-autosuggestions
bindkey '^y' autosuggest-accept
# fzf
source <(fzf --zsh)
